### ISSUE TITLE
Misaligned segments in playlists

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-wowza#19]
I got the Livepeer transcoding working with the Wowza plugin and a SMIL file. But the segments in the playlists of the two renditions were misaligned:

```
junkyard-dog:~ dob$ curl http://ec2---------------------.compute.amazonaws.com:1935/live/doblive.smil/manifest.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1920x1080
chunklist_w721451849_b2500000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=700000,RESOLUTION=640x360
chunklist_w721451849_b700000.m3u8
junkyard-dog:~ dob$ 
junkyard-dog:~ dob$ 
junkyard-dog:~ dob$ curl http://ec2---------------------.compute.amazonaws.com:1935/live/doblive.smil/chunklist_w676469426_b2500000.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:12
#EXT-X-MEDIA-SEQUENCE:48
#EXTINF:10.0,
media_w676469426_b2500000_48.ts
#EXTINF:10.0,
media_w676469426_b2500000_49.ts
#EXTINF:10.0,
media_w676469426_b2500000_50.ts
junkyard-dog:~ dob$ 
junkyard-dog:~ dob$ 
junkyard-dog:~ dob$ curl http://ec2---------------------compute.amazonaws.com:1935/live/doblive.smil/chunklist_w1489915020_b700000.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:12
#EXT-X-MEDIA-SEQUENCE:43
#EXTINF:10.0,
media_w1489915020_b700000_43.ts
#EXTINF:10.0,
media_w1489915020_b700000_44.ts
#EXTINF:10.0,
media_w1489915020_b700000_45.ts
junkyard-dog:~ dob$ 
```

Note rendition 1 is showing segments 48-50, and rendition 2 is showing segments 43-45. The result is that the Livepeer player chokes when switching between them and just pauses with console errors, before eventually, after enough time passes, resuming playback on the selected rendition. The JWPlayer test player was also acting similarly weird.

Of course this could have something to do with my own misconfiguration of SIML files or Wowza generally.

Note, the 1080p stream is the original source file from Wowza, and the 360p stream is ingested from Livepeer, via the installer's configuration.

**Comment by iameli** [comment]
Got it, thanks for the report! This will take a bit of pondering to handle appropriately - do we want to just buffer the source stream's output until the transcoded renditions are ready to go? Probable, but I can imagine a few different use cases. Possibly something that should be configurable.

As a workaround, if your Wowza bitrate ladder specifies a rendition with video passthrough, it should create a `${streamName}_source.stream` stream file which corresponds to the "source" rendition provided by go-livepeer. This results in an unnecessary round-trip to the Livepeer servers but that rendition should be in sync with the others.

**Comment by f1l1b0x** [comment]
The source needs to be align to outputs and outputs need to be watched for discontinuities.

**Comment by iameli** [comment]
This now appears to be exclusively happening on inputs with variable keyframe intervals.
