### ISSUE TITLE
Hardening: handle migration to a different broadcaster

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-wowza#23]
@iameli commented on [Fri Aug 09 2019](https://github.com/livepeer/livepeerjs/issues/442)

If a broadcaster goes down, we should re-request the list of broadcasters, pick a new one, and switch everything (Stream Files, PushPublishCupertinoHandler) over to that one.

**Comment by j0sh** [comment]
There's a couple ways to handle this. I'm assuming a "re-request" here is a network request to fetch a fresh list of broadcasters.

1. Have a list of broadcasters ready in advance. This can be a single list that's fetched periodically (say, at startup then once per hour) and could also be refreshed when Wowza detects it's "running low" or hitting some load threshold. This minimizes the amount of interaction that occurs when a new transcoding job needs to start, and offers the most resiliency to the downtime of whatever is serving the B list. If a single broadcaster goes down, the next one on the list can be used immediately; no need for another network request to re-fetch the list.

2. Fetch the same list of broadcasters during the beginning of the stream. This may help if we think the set of broadcasters could vary significantly between streams, and we want to use this as a load balancing mechanism.

3. Request a broadcaster each time a stream comes in, and re-request for each time a B goes down - which seems to be the implied behavior here.
