### ISSUE TITLE
Testing: implement end-to-end black box testing

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-wowza#24]
Steps:

1. Build a new version of the livepeer-wowza container using the Dockerfile
1. Deploy it to a staging environment
1. Stream in Big Buck Bunny
1. Download all transcoded renditions
1. Basic check to make sure the renditions looks reasonable

**Comment by iameli** [comment]
I forgot this existed as a ticket - @darkdarkdragon is working on this exact thing now.

**Comment by darkdarkdragon** [comment]
I want to run two sets of tests. Each test should report success/failure to Discord channel.
1. One-off test - streams one video file (10 min), reads segments back, calculates latencies.
   Main goal is to check that latencies not exceeding some threshold.
2. Infinite-running test. Streaming video, reading back segments.
   Main question is what to define as failure?
   Wowza can miss some starting segments in some renditions - this probably isn't a failure.
   There can be gaps in segment's timestamps - this is probably failure.
   Also, timestamps could drift in different media streams. Apple's HLS validation tool
   shows error if drift is more than 2 second.
   1. So, should we too consider drift for more than two seconds to be failure?
   2. Should we stop test if failure detected?

**Comment by darkdarkdragon** [comment]
@iameli @j0sh What do you think? Especially about timestamps drifting issue?

**Comment by wohlner** [comment]
This work is captured in other tickets. Closing now.
